spring:
  application:
    name: serviceIntegration

server:
  error:
    whitelabel:
      enabled: false
  port: 9081
  servlet:
    context-path: /serviceIntegration


baseUrl: http://localhost:9081/serviceIntegration/trace/
#baseUrl: http://:8080/traceIntegration/trace/
esbUrl: http://52.118.255.135:7800



#baseUrl: http://:7443/traceIntegration/trace/
#esbUrl: http://:7800
