spring:
  application:
    name: priceService

server:
  error:
    whitelabel:
      enabled: false
  port: 9081
  servlet:
    context-path: /priceService

log4j:
  logger:
    org:
      springframework=ALL:
price.baseUrl: http://localhost:9081/priceService/price/
#baseUrl: http://:8080/traceIntegration/trace/
esbUrl: http://52.118.255.135:7800



#baseUrl: http://:7443/traceIntegration/trace/
#esbUrl: http://:7800
